---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver-config:
      image: chef/ubuntu-12.04
      platform: ubuntu

suites:
  - name: default
    run_list:
      - recipe[joad-ci::default]
    attributes:
