name             'joad-ci'
maintainer       'Takahiro Yano'
maintainer_email 'Yano_Takahiro@ogis-ri.co.jp'
license          'MIT'
description      'Installs/Configures joad-ci'
long_description 'Installs/Configures joad-ci'
version          '0.1.0'

depends 'jenkins'
depends 'docker'
